[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>", "fmg"]
description = "Slide decks managed by deckz."
homepage = "https://github.com/m09/formations"
license = "Apache-2.0"
name = "slides"
version = "1.0.0"

[tool.poetry.dependencies]
Pygments = "^2.9.0"
matplotlib = "^3.5.1"
plots = {path = "figures/plt", develop = true}
python = ">= 3.8, < 3.11"
deckz = "^17.2.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^3.9.2"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
isort = "^5.9.1"
mypy = "^0.812"
pylint = "^2.8.2"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
