[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>", "fmg"]
description = "Slide decks managed by deckz."
homepage = "https://github.com/m09/formations"
license = "Apache-2.0"
name = "slides"
version = "1.0.0"

[tool.poetry.dependencies]
Pygments = "^2.6.1"
python = "^3.6"
deckz = "^11.0.0"


[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
flake8 = "^3.8.4"
[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
