model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=1000, output_dim=64))
model.add(tf.keras.layers.SimpleRNN(128))
model.add(tf.keras.layers.Dense(10, activation="softmax"))
model.summary()
