[tool.poetry]
authors = ["mlambda <142691+m09@users.noreply.github.com>"]
description = ""
name = "plots"
version = "0.1.0"

[tool.poetry.dependencies]
matplotlib = "^3.5.1"
python = ">= 3.8, < 3.11"
scikit-learn = "^1.0.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^3.9.2"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
isort = "^5.9.1"
mypy = "^0.812"
pylint = "^2.8.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
