default_titles:
  deployment: Deployment
  environment: Software environment management
  packaging: Python packages creation
  cli: Command line interfaces
flavors:
  full:
    - environment
    - /en/questions
    - demo-environment
    - packaging
    - /en/questions
    - tp-packaging
    - deployment
    - /en/questions
    - cli
    - /en/questions
    - tp-cli-stegano
  light:
    - environment
    - /en/questions
    - demo-environment
    - packaging
    - /en/questions
    - tp-packaging
    - cli
    - /en/questions
    - tp-cli
title: Python software engineering
