[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
description = "Tool to handle multiple beamer decks."
name = "deckz"
readme = "README.md"
version = "10.3.0"

[tool.poetry.dependencies]
python = "^3.9"
typer = {version = "^0.7.0", extras = ["all"]}

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[tool.poetry.scripts]
deckz = 'deckz.cli:main'

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
